version: "2.3"
services:
  mysql-db:
    image: jmj1380/shootingminer-db:latest
    container_name: game-db-02
    environment:
      MYSQL_ROOT_PASSWORD: dnjfska@33
      MYSQL_USER: api_server
      MYSQL_PASSWORD: api_pass
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 60s
      timeout: 120s
      retries: 5

  spring-boot-app:
    image: jmj1380/shootingminer-server:holly
    container_name: game-server-02
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/ShootingMinerDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: api_server
      SPRING_DATASOURCE_PASSWORD: api_pass
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy